#!/usr/bin/env node
/**
 * Generator for Spanish word banks. Run once to create es-kid.mjs, es-adult.mjs, es-wise.mjs
 */

function normalize(word) {
  return word
    .toUpperCase()
    .replace(/Ñ/g, 'N')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^A-Z]/g, '');
}

function buildEntries(pairs) {
  const seen = new Set();
  const entries = [];
  for (const [rawWord, clue] of pairs) {
    const word = normalize(rawWord);
    if (!word || word.length < 2) continue;
    if (seen.has(word)) continue;
    seen.add(word);
    entries.push({ word, clue });
  }
  return entries;
}

function writeBank(filename, entries, expectedCount) {
  if (entries.length !== expectedCount) {
    throw new Error(`${filename}: expected ${expectedCount}, got ${entries.length}`);
  }
  const lines = entries.map(
    (e) => `  { word: "${e.word}", clue: "${e.clue.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}" }`
  );
  const content = `export default [\n${lines.join(',\n')},\n];\n`;
  return { filename, content };
}

// ─── KID (200) ───────────────────────────────────────────────────────────────
const kidPairs = [
  ['sol', 'Brilla en el cielo de día'],
  ['luna', 'Brilla en el cielo de noche'],
  ['mar', 'Agua salada muy grande'],
  ['ola', 'Sube y baja en la playa'],
  ['pez', 'Animal que nada con aletas'],
  ['gato', 'Mascota que maúlla'],
  ['perro', 'Mejor amigo que ladra'],
  ['casa', 'Lugar donde vives'],
  ['pan', 'Se come en el desayuno'],
  ['leche', 'Bebida blanca de la vaca'],
  ['agua', 'Líquido para beber'],
  ['fuego', 'Quema y da calor'],
  ['tierra', 'Donde plantamos flores'],
  ['aire', 'Lo respiramos siempre'],
  ['árbol', 'Planta alta con hojas'],
  ['flor', 'Planta bonita y colorida'],
  ['hoja', 'Parte verde del árbol'],
  ['rama', 'Brazo del árbol'],
  ['raíz', 'Parte del árbol bajo tierra'],
  ['semilla', 'Pequeña y da una planta'],
  ['fruta', 'Alimento dulce del árbol'],
  ['manzana', 'Fruta roja o verde'],
  ['pera', 'Fruta verde en forma de lágrima'],
  ['uva', 'Fruta pequeña en racimo'],
  ['plátano', 'Fruta amarilla alargada'],
  ['naranja', 'Fruta cítrica naranja'],
  ['fresa', 'Fruta roja pequeña'],
  ['sandía', 'Fruta grande y roja por dentro'],
  ['melón', 'Fruta redonda y dulce'],
  ['zanahoria', 'Verdura naranja de conejo'],
  ['patata', 'Tubérculo para freír'],
  ['tomate', 'Verdura roja para ensalada'],
  ['lechuga', 'Verdura verde de ensalada'],
  ['pan', 'Alimento hecho con harina'],
  ['queso', 'Producto lácteo amarillo'],
  ['huevo', 'Lo ponen las gallinas'],
  ['miel', 'Dulce hecho por abejas'],
  ['azúcar', 'Hace dulce la comida'],
  ['sal', 'Saboriza la comida'],
  ['sopa', 'Comida caliente líquida'],
  ['arroz', 'Grano blanco de comer'],
  ['pasta', 'Comida italiana de harina'],
  ['carne', 'Alimento del animal'],
  ['pescado', 'Comida del mar'],
  ['pollo', 'Ave que ponen huevos'],
  ['vaca', 'Animal que da leche'],
  ['cerdo', 'Animal rosado de granja'],
  ['oveja', 'Animal con lana blanca'],
  ['caballo', 'Animal grande para montar'],
  ['burro', 'Animal de granja con orejas largas'],
  ['conejo', 'Animal con orejas largas que salta'],
  ['ratón', 'Roedor pequeño gris'],
  ['elefante', 'Animal enorme con trompa'],
  ['león', 'Rey de la selva'],
  ['tigre', 'Felino con rayas'],
  ['oso', 'Animal grande y peludo'],
  ['mono', 'Animal que trepa árboles'],
  ['jirafa', 'Animal con cuello muy largo'],
  ['cebra', 'Caballo con rayas blancas y negras'],
  ['delfín', 'Mamífero amigo del mar'],
  ['ballena', 'Animal gigante del océano'],
  ['tiburón', 'Pez grande del mar'],
  ['pulpo', 'Animal marino con ocho brazos'],
  ['mariposa', 'Insecto con alas de colores'],
  ['abeja', 'Insecto que hace miel'],
  ['hormiga', 'Insecto pequeño muy trabajador'],
  ['araña', 'Tiene ocho patas y hace telas'],
  ['mosca', 'Insecto que zumba'],
  ['mosquito', 'Insecto que pica'],
  ['pájaro', 'Animal con plumas que vuela'],
  ['águila', 'Ave rapaz muy grande'],
  ['loro', 'Ave de colores que habla'],
  ['gallina', 'Ave de corral que cacarea'],
  ['gallo', 'Canta al amanecer'],
  ['pato', 'Ave que nada en el lago'],
  ['cisne', 'Ave blanca y elegante'],
  ['pez', 'Vive en el agua'],
  ['rana', 'Salta y vive en el charco'],
  ['serpiente', 'Reptil largo sin patas'],
  ['tortuga', 'Reptil con caparazón'],
  ['lagarto', 'Reptil pequeño de pared'],
  ['cocodrilo', 'Reptil grande con dientes'],
  ['dinosaurio', 'Animal gigante extinto'],
  ['niño', 'Persona pequeña en edad'],
  ['niña', 'Chica pequeña'],
  ['bebé', 'Persona muy pequeña'],
  ['mamá', 'Madre de la familia'],
  ['papá', 'Padre de la familia'],
  ['abuelo', 'Padre de papá o mamá'],
  ['abuela', 'Madre de papá o mamá'],
  ['hermano', 'Hijo de los mismos padres'],
  ['hermana', 'Hija de los mismos padres'],
  ['tío', 'Hermano de papá o mamá'],
  ['tía', 'Hermana de papá o mamá'],
  ['primo', 'Hijo de tío o tía'],
  ['amigo', 'Persona que quieres mucho'],
  ['amiga', 'Compañera querida'],
  ['maestro', 'Enseña en la escuela'],
  ['maestra', 'Profesora del colegio'],
  ['escuela', 'Lugar para aprender'],
  ['libro', 'Tiene páginas para leer'],
  ['lápiz', 'Sirve para escribir'],
  ['bolígrafo', 'Escribe con tinta'],
  ['goma', 'Borra lo escrito'],
  ['regla', 'Sirve para medir líneas'],
  ['mochila', 'Bolsa para llevar libros'],
  ['pizarra', 'Donde escribe el maestro'],
  ['mesa', 'Mueble con patas para comer'],
  ['silla', 'Mueble para sentarse'],
  ['cama', 'Mueble para dormir'],
  ['sofá', 'Mueble cómodo del salón'],
  ['puerta', 'Abre y cierra la entrada'],
  ['ventana', 'Cristal para ver afuera'],
  ['techo', 'Cubre la casa arriba'],
  ['suelo', 'Donde pisamos en casa'],
  ['pared', 'Separa las habitaciones'],
  ['cocina', 'Habitación para cocinar'],
  ['baño', 'Habitación para asearse'],
  ['salón', 'Habitación para estar'],
  ['jardín', 'Espacio con plantas en casa'],
  ['calle', 'Camino por donde pasan coches'],
  ['parque', 'Lugar con árboles para jugar'],
  ['playa', 'Arena junto al mar'],
  ['montaña', 'Tierra muy alta'],
  ['río', 'Agua que fluye a la mar'],
  ['lago', 'Agua dulce rodeada de tierra'],
  ['bosque', 'Lugar con muchos árboles'],
  ['campo', 'Tierra abierta fuera de ciudad'],
  ['ciudad', 'Lugar con muchas casas'],
  ['pueblo', 'Lugar pequeño con casas'],
  ['coche', 'Vehículo con cuatro ruedas'],
  ['autobús', 'Transporte grande de pasajeros'],
  ['tren', 'Va por las vías de hierro'],
  ['avión', 'Vuela por el cielo'],
  ['barco', 'Navega por el mar'],
  ['bicicleta', 'Vehículo de dos ruedas'],
  ['patinete', 'Tabla con ruedas para niños'],
  ['pelota', 'Objeto redondo para jugar'],
  ['muñeca', 'Juguete de niña'],
  ['coche', 'Juguete con ruedas'],
  ['bloque', 'Pieza de construcción'],
  ['puzzle', 'Juego de piezas que encajan'],
  ['carta', 'Juego con baraja'],
  ['dado', 'Cubo con números para jugar'],
  ['cometa', 'Vuela con el viento'],
  ['globo', 'Bolsita de aire de fiesta'],
  ['regalo', 'Sorpresa en tu cumpleaños'],
  ['fiesta', 'Celebración con amigos'],
  ['tarta', 'Pastel de cumpleaños'],
  ['vela', 'Se enciende en la tarta'],
  ['juguete', 'Objeto para divertirse'],
  ['juego', 'Actividad para pasarlo bien'],
  ['deporte', 'Actividad física con reglas'],
  ['fútbol', 'Deporte con balón y portería'],
  ['baloncesto', 'Deporte con canasta'],
  ['natación', 'Deporte en el agua'],
  ['correr', 'Moverse muy rápido a pie'],
  ['saltar', 'Subir del suelo con los pies'],
  ['bailar', 'Mover el cuerpo con música'],
  ['cantar', 'Hacer música con la voz'],
  ['dibujar', 'Hacer imágenes con lápiz'],
  ['pintar', 'Colorear con pinceles'],
  ['leer', 'Mirar las palabras de un libro'],
  ['escribir', 'Poner letras en el papel'],
  ['contar', 'Decir números en orden'],
  ['sumar', 'Juntar dos números'],
  ['restar', 'Quitar un número de otro'],
  ['número', 'Símbolo para contar'],
  ['uno', 'Primer número'],
  ['dos', 'Número después del uno'],
  ['tres', 'Número después del dos'],
  ['cuatro', 'Número después del tres'],
  ['cinco', 'Número después del cuatro'],
  ['seis', 'Número después del cinco'],
  ['siete', 'Número después del seis'],
  ['ocho', 'Número después del siete'],
  ['nueve', 'Número después del ocho'],
  ['diez', 'Número después del nueve'],
  ['rojo', 'Color de la manzana'],
  ['azul', 'Color del cielo'],
  ['verde', 'Color de la hierba'],
  ['amarillo', 'Color del sol'],
  ['naranja', 'Color entre rojo y amarillo'],
  ['morado', 'Color de la uva'],
  ['rosa', 'Color suave y dulce'],
  ['negro', 'Color de la noche'],
  ['blanco', 'Color de la nieve'],
  ['gris', 'Color de las nubes'],
  ['marrón', 'Color de la tierra'],
  ['día', 'Cuando brilla el sol'],
  ['noche', 'Cuando sale la luna'],
  ['mañana', 'Primera parte del día'],
  ['tarde', 'Después del mediodía'],
  ['hora', 'Medida del tiempo'],
  ['minuto', 'Sesenta segundos'],
  ['semana', 'Siete días seguidos'],
  ['mes', 'Treinta días aproximadamente'],
  ['año', 'Doce meses'],
  ['lunes', 'Primer día de la semana'],
  ['martes', 'Segundo día de la semana'],
  ['miércoles', 'Día del medio de semana'],
  ['jueves', 'Cuarto día de la semana'],
  ['viernes', 'Último día de clase'],
  ['sábado', 'Día de descanso'],
  ['domingo', 'Último día de la semana'],
  ['enero', 'Primer mes del año'],
  ['febrero', 'Mes más corto del año'],
  ['marzo', 'Mes de la primavera'],
  ['abril', 'Mes de lluvias'],
  ['mayo', 'Quinto mes del año'],
  ['junio', 'Mes del verano'],
  ['julio', 'Mes de vacaciones'],
  ['agosto', 'Mes muy caluroso'],
  ['sol', 'Estrella que nos da luz'],
  ['estrella', 'Brilla en el cielo nocturno'],
  ['nube', 'Blanca o gris en el cielo'],
  ['lluvia', 'Agua que cae del cielo'],
  ['nieve', 'Agua blanca y fría'],
  ['viento', 'Aire que mueve las hojas'],
  ['trueno', 'Ruido fuerte de tormenta'],
  ['rayo', 'Luz eléctrica en tormenta'],
  ['arcoíris', 'Colores en el cielo tras lluvia'],
  ['calor', 'Temperatura alta'],
  ['frío', 'Temperatura baja'],
  ['ropa', 'Lo que nos ponemos'],
  ['camisa', 'Prenda de manga'],
  ['pantalón', 'Prenda para las piernas'],
  ['zapato', 'Calzado para los pies'],
  ['calcetín', 'Cubre el pie dentro del zapato'],
  ['sombrero', 'Se pone en la cabeza'],
  ['guante', 'Cubre la mano en invierno'],
  ['abrigo', 'Ropa caliente de invierno'],
  ['vestido', 'Prenda de una pieza'],
  ['falda', 'Prenda para la cintura'],
  ['mano', 'Parte del cuerpo con dedos'],
  ['pie', 'Parte del cuerpo para caminar'],
  ['cabeza', 'Parte superior del cuerpo'],
  ['ojo', 'Sirve para ver'],
  ['nariz', 'Sirve para oler'],
  ['boca', 'Sirve para comer y hablar'],
  ['oreja', 'Sirve para oír'],
  ['diente', 'Blanco en la boca'],
  ['pelo', 'Crece en la cabeza'],
  ['brazo', 'Une hombro y mano'],
  ['pierna', 'Une cadera y pie'],
  ['corazón', 'Bombea la sangre'],
  ['sonrisa', 'Muestra felicidad en la cara'],
  ['llorar', 'Salen lágrimas de los ojos'],
  ['reír', 'Expresión de alegría'],
  ['dormir', 'Descansar con los ojos cerrados'],
  ['comer', 'Meter comida en la boca'],
  ['beber', 'Tomar líquido'],
  ['hablar', 'Decir palabras'],
  ['escuchar', 'Prestar atención al oído'],
  ['ver', 'Usar los ojos'],
  ['oler', 'Usar la nariz'],
  ['tocar', 'Usar las manos'],
  ['caminar', 'Moverse a pie despacio'],
  ['correr', 'Ir rápido a pie'],
  ['saltar', 'Elevarse del suelo'],
  ['nadar', 'Moverse en el agua'],
  ['volar', 'Moverse por el aire'],
  ['grande', 'De tamaño mayor'],
  ['pequeño', 'De tamaño menor'],
  ['alto', 'De mucha altura'],
  ['bajo', 'De poca altura'],
  ['largo', 'De mucha distancia'],
  ['corto', 'De poca distancia'],
  ['nuevo', 'Recién hecho o comprado'],
  ['viejo', 'De muchos años'],
  ['bonito', 'Agradable a la vista'],
  ['feo', 'No agradable a la vista'],
  ['bueno', 'De calidad positiva'],
  ['malo', 'De calidad negativa'],
  ['feliz', 'Contento y alegre'],
  ['triste', 'Con pena o melancolía'],
  ['amor', 'Sentimiento de cariño'],
  ['paz', 'Tranquilidad sin guerra'],
  ['música', 'Sonidos agradables'],
  ['canción', 'Música con letra'],
  ['baile', 'Moverse al ritmo'],
  ['cuento', 'Historia para niños'],
  ['historia', 'Relato de hechos'],
  ['película', 'Historia en la pantalla'],
  ['televisión', 'Aparece en el salón'],
  ['radio', 'Suena música y noticias'],
  ['teléfono', 'Sirve para llamar'],
  ['ordenador', 'Máquina para trabajar'],
  ['foto', 'Imagen capturada'],
  ['cámara', 'Sirve para hacer fotos'],
  ['reloj', 'Marca la hora'],
  ['llave', 'Abre la puerta'],
  ['bolsa', 'Sirve para guardar cosas'],
  ['caja', 'Recipiente con tapa'],
  ['vaso', 'Sirve para beber'],
  ['plato', 'Donde ponemos la comida'],
  ['cuchara', 'Utensilio para sopa'],
  ['tenedor', 'Utensilio con púas'],
  ['cuchillo', 'Utensilio para cortar'],
  ['escoba', 'Limpia el suelo'],
  ['jabón', 'Limpia las manos'],
  ['toalla', 'Seca el cuerpo'],
  ['cepillo', 'Limpia el pelo o dientes'],
  ['diente', 'Se lava con pasta'],
  ['pastel', 'Dulce de horno'],
  ['galleta', 'Dulce crujiente'],
  ['chocolate', 'Dulce marrón muy rico'],
  ['caramelo', 'Dulce pequeño de azúcar'],
  ['helado', 'Postre frío y dulce'],
  ['zumo', 'Bebida de fruta'],
  ['té', 'Bebida caliente'],
  ['café', 'Bebida amarga de adultos'],
  ['madera', 'Material de los árboles'],
  ['piedra', 'Roca pequeña'],
  ['arena', 'Granos de la playa'],
  ['hierro', 'Metal muy duro'],
  ['oro', 'Metal amarillo precioso'],
  ['plata', 'Metal blanco brillante'],
  ['papel', 'Material para escribir'],
  ['tijeras', 'Cortan el papel'],
  ['pegamento', 'Une dos cosas'],
  ['cuerda', 'Hilo grueso para atar'],
  ['luz', 'Ilumina la habitación'],
  ['sombra', 'Zona sin luz'],
  ['espejo', 'Refleja tu imagen'],
  ['lámpara', 'Da luz en la noche'],
  ['vela', 'Ilumina con fuego pequeño'],
  ['campana', 'Hace ding dong'],
  ['campana', 'Instrumento que suena'],
  ['tambor', 'Instrumento de percusión'],
  ['flauta', 'Instrumento de viento'],
  ['guitarra', 'Instrumento de cuerdas'],
  ['piano', 'Instrumento con teclas'],
  ['tren', 'Chu chu por las vías'],
  ['barco', 'Navega en el agua'],
  ['cohete', 'Va al espacio'],
  ['planeta', 'Tierra es uno de ellos'],
  ['espacio', 'Donde están las estrellas'],
  ['mapa', 'Dibuja lugares del mundo'],
  ['bandera', 'Símbolo de un país'],
  ['España', 'País donde hablamos español'],
  ['mundo', 'Planeta donde vivimos'],
  ['isla', 'Tierra rodeada de agua'],
  ['volcán', 'Montaña que echa fuego'],
  ['cueva', 'Hueco en la montaña'],
  ['puente', 'Une dos orillas'],
  ['torre', 'Edificio muy alto'],
  ['castillo', 'Fortaleza de reyes'],
  ['rey', 'Gobernante de un reino'],
  ['reina', 'Esposa del rey'],
  ['príncipe', 'Hijo del rey'],
  ['princesa', 'Hija del rey'],
  ['caballero', 'Guerrero con armadura'],
  ['dragón', 'Monstruo de cuentos'],
  ['hada', 'Ser mágico de cuentos'],
  ['bruja', 'Mujer mágica de cuentos'],
  ['mago', 'Hace trucos de magia'],
  ['tesoro', 'Oro escondido'],
  ['pirata', 'Ladrón del mar'],
  ['tesoro', 'Cofre con joyas'],
  ['mapa', 'Guía para encontrar tesoro'],
  ['aventura', 'Experiencia emocionante'],
  ['secreto', 'Algo que no se cuenta'],
  ['sueño', 'Imágenes al dormir'],
  ['esperanza', 'Creer que algo bueno vendrá'],
  ['valiente', 'Sin miedo'],
  ['amable', 'Trata bien a los demás'],
  ['honesto', 'Dice la verdad'],
  ['trabajo', 'Lo que hacen los adultos'],
  ['ayuda', 'Colaborar con alguien'],
  ['gracias', 'Palabra de agradecimiento'],
  ['hola', 'Saludo al encontrarse'],
  ['adiós', 'Despedida al irse'],
  ['sí', 'Respuesta afirmativa'],
  ['no', 'Respuesta negativa'],
  ['por favor', 'Palabra de cortesía'],
  ['perdón', 'Pedir disculpas'],
  ['nombre', 'Cómo te llaman'],
  ['apellido', 'Segundo nombre de familia'],
  ['edad', 'Años que tienes'],
  ['cumpleaños', 'Día en que naciste'],
  ['regalo', 'Obsequio de cumpleaños'],
  ['familia', 'Padres, hijos y parientes'],
  ['hogar', 'Lugar donde vives con amor'],
  ['vecino', 'Persona de la casa de al lado'],
  ['amistad', 'Relación entre amigos'],
  ['escuela', 'Donde aprendes letras'],
  ['clase', 'Grupo de alumnos'],
  ['tarea', 'Deberes para casa'],
  ['examen', 'Prueba en el colegio'],
  ['nota', 'Calificación del examen'],
  ['aprender', 'Adquirir conocimiento'],
  ['enseñar', 'Transmitir conocimiento'],
  ['pregunta', 'Lo que quieres saber'],
  ['respuesta', 'Lo que contestas'],
  ['verdad', 'Lo que es real'],
  ['mentira', 'Lo que no es verdad'],
  ['juego', 'Diversión con reglas'],
  ['equipo', 'Grupo que juega junto'],
  ['ganar', 'Ser el primero'],
  ['perder', 'No ganar el juego'],
  ['empate', 'Mismo resultado para ambos'],
  ['meta', 'Lugar donde termina la carrera'],
  ['trofeo', 'Premio por ganar'],
  ['medalla', 'Premio de metal'],
  ['estrella', 'Símbolo de logro'],
  ['orgullo', 'Sentirse satisfecho'],
  ['miedo', 'Sensación de peligro'],
  ['valor', 'Coraje ante el miedo'],
  ['sorpresa', 'Algo inesperado'],
  ['magia', 'Trucos imposibles'],
  ['fantasía', 'Mundo de imaginación'],
  ['imaginar', 'Crear en la mente'],
  ['crear', 'Hacer algo nuevo'],
  ['construir', 'Armar piezas juntas'],
  ['romper', 'Partir en pedazos'],
  ['abrir', 'Quitar lo que cierra'],
  ['cerrar', 'Tapar la entrada'],
  ['entrar', 'Pasar hacia adentro'],
  ['salir', 'Pasar hacia afuera'],
  ['subir', 'Ir hacia arriba'],
  ['bajar', 'Ir hacia abajo'],
  ['venir', 'Llegar aquí'],
  ['ir', 'Moverse a otro lugar'],
  ['llegar', 'Alcanzar el destino'],
  ['empezar', 'Comenzar algo'],
  ['terminar', 'Acabar algo'],
  ['esperar', 'Aguardar un momento'],
  ['buscar', 'Intentar encontrar'],
  ['encontrar', 'Dar con algo perdido'],
  ['perder', 'No saber dónde está'],
  ['guardar', 'Poner en lugar seguro'],
  ['dar', 'Entregar a alguien'],
  ['recibir', 'Aceptar lo que dan'],
  ['compartir', 'Repartir con otros'],
  ['cuidar', 'Proteger y atender'],
  ['amar', 'Querer mucho'],
  ['querer', 'Desear o apreciar'],
  ['necesitar', 'Requerir algo'],
  ['tener', 'Poseer algo'],
  ['ser', 'Existir o ser algo'],
  ['estar', 'Encontrarse en un lugar'],
  ['hacer', 'Realizar una acción'],
  ['poder', 'Ser capaz de algo'],
  ['saber', 'Conocer información'],
  ['pensar', 'Usar la mente'],
  ['recordar', 'Traer a la memoria'],
  ['olvidar', 'No recordar'],
  ['soñar', 'Imaginar al dormir'],
  ['despertar', 'Dejar de dormir'],
  ['desayunar', 'Primera comida del día'],
  ['almorzar', 'Comida del mediodía'],
  ['cenar', 'Última comida del día'],
  ['merendar', 'Comer por la tarde'],
  ['hambre', 'Ganas de comer'],
  ['sed', 'Ganas de beber'],
  ['cansancio', 'Necesidad de descansar'],
  ['energía', 'Fuerza para actuar'],
  ['fuerza', 'Poder físico'],
  ['velocidad', 'Rapidez al moverse'],
  ['silencio', 'Ausencia de ruido'],
  ['ruido', 'Sonido fuerte'],
  ['voz', 'Sonido al hablar'],
  ['palabra', 'Unidad del lenguaje'],
  ['letra', 'Símbolo del alfabeto'],
  ['frase', 'Grupo de palabras'],
  ['idioma', 'Lengua de un pueblo'],
  ['español', 'Idioma de España'],
  ['inglés', 'Idioma de Inglaterra'],
  ['animal', 'Ser vivo que se mueve'],
  ['planta', 'Ser vivo que crece'],
  ['vida', 'Estar vivo'],
  ['nacer', 'Empezar a vivir'],
  ['crecer', 'Hacerse más grande'],
  ['vivir', 'Tener vida'],
  ['morir', 'Dejar de vivir'],
  ['naturaleza', 'Bosques, ríos y animales'],
  ['cielo', 'Espacio sobre la tierra'],
  ['suelo', 'Tierra bajo los pies'],
  ['piedra', 'Roca del suelo'],
  ['monte', 'Colina grande'],
  ['colina', 'Elevación de tierra'],
  ['valle', 'Tierra baja entre montañas'],
  ['pradera', 'Campo con hierba'],
  ['desierto', 'Lugar seco y caliente'],
  ['selva', 'Bosque tropical denso'],
  ['jungla', 'Bosque con muchos animales'],
  ['océano', 'Mar muy grande'],
  ['costa', 'Orilla del mar'],
  ['arena', 'Polvo de la playa'],
  ['concha', 'Casa del caracol marino'],
  ['caracol', 'Animal lento con concha'],
  ['cangrejo', 'Animal con pinzas'],
  ['estrella de mar', 'Animal marino en forma de estrella'],
  ['medusa', 'Animal gelatinoso del mar'],
  ['caballo de mar', 'Pequeño pez con forma curiosa'],
  ['pingüino', 'Ave que no vuela del frío'],
  ['foca', 'Mamífero marino juguetón'],
  ['morsa', 'Animal marino con colmillos'],
  ['camello', 'Animal del desierto con jorobas'],
  ['canguro', 'Salta con bolsa para crías'],
  ['koala', 'Oso australiano de eucalipto'],
  ['panda', 'Oso blanco y negro'],
  ['mapache', 'Animal con antifaz'],
  ['zorro', 'Animal astuto del bosque'],
  ['lobo', 'Animal que aúlla'],
  ['ciervo', 'Animal con astas'],
  ['jabalí', 'Cerdo salvaje'],
  ['ardilla', 'Roedor que guarda nueces'],
  ['castor', 'Animal que construye presas'],
  ['murciélago', 'Mamífero que vuela de noche'],
  ['búho', 'Ave nocturna sabia'],
  ['paloma', 'Ave blanca de la paz'],
  ['gorrión', 'Pájaro pequeño urbano'],
  ['canario', 'Ave amarilla cantora'],
  ['colibrí', 'Ave diminuta que zumba'],
  ['tucán', 'Ave tropical con pico grande'],
  ['flamenco', 'Ave rosa de una pata'],
  ['avestruz', 'Ave grande que no vuela'],
  ['gallina', 'Ave que pone huevos'],
  ['pavo', 'Ave grande de Acción de Gracias'],
  ['abeja', 'Hace miel en la colmena'],
  ['mariposa', 'Sale de la crisálida'],
  ['oruga', 'Larva antes de mariposa'],
  ['escarabajo', 'Insecto con caparazón duro'],
  ['grillo', 'Insecto que canta de noche'],
  ['saltamontes', 'Insecto que salta lejos'],
  ['libélula', 'Insecto volador del agua'],
  ['caracol', 'Deja rastro de baba'],
  ['lombriz', 'Gusano de la tierra'],
  ['medusa', 'Pica en la playa a veces'],
  ['coral', 'Formación del fondo marino'],
  ['algas', 'Plantas del mar'],
  ['musgo', 'Planta verde en las piedras'],
  ['helecho', 'Planta con hojas rizadas'],
  ['cactus', 'Planta con espinas del desierto'],
  ['rosa', 'Flor con espinas en el tallo'],
  ['tulipán', 'Flor de primavera colorida'],
  ['girasol', 'Flor amarilla que sigue al sol'],
  ['margarita', 'Flor blanca con centro amarillo'],
  ['clavel', 'Flor olorosa de San Jordi'],
  ['jazmín', 'Flor blanca muy perfumada'],
  ['violeta', 'Flor pequeña morada'],
  ['orquídea', 'Flor exótica y elegante'],
  ['lavanda', 'Planta morada aromática'],
  ['menta', 'Hierba fresca para infusiones'],
  ['albahaca', 'Hierba aromática de cocina'],
  ['perejil', 'Hierba verde de decorar'],
  ['cebolla', 'Verdura que hace llorar'],
  ['ajo', 'Condimento fuerte y blanco'],
  ['pimiento', 'Verdura roja o verde'],
  ['calabaza', 'Verdura naranja de Halloween'],
  ['berenjena', 'Verdura morada alargada'],
  ['pepino', 'Verdura verde y fresca'],
  ['apio', 'Verdura crujiente larga'],
  ['espinaca', 'Verdura verde de Popeye'],
  ['brócoli', 'Verdura verde en ramilletes'],
  ['col', 'Verdura redonda de hojas'],
  ['maíz', 'Planta amarilla en mazorca'],
  ['trigo', 'Cereal para hacer pan'],
  ['avena', 'Cereal para gachas'],
  ['mantequilla', 'Grasa amarilla de la leche'],
  ['mermelada', 'Dulce de fruta para pan'],
  ['miel', 'Dulce dorado de abejas'],
  ['yogur', 'Lácteo fermentado'],
  ['natillas', 'Postre cremoso amarillo'],
  ['flan', 'Postre de huevo y caramelo'],
  ['bizcocho', 'Pastel esponjoso'],
  ['tarta', 'Pastel de cumpleaños'],
  ['donut', 'Rosquilla dulce con agujero'],
  ['churro', 'Dulce frito alargado'],
  ['palomitas', 'Maíz explotado de cine'],
  ['patatas fritas', 'Snack crujiente de patata'],
  ['sándwich', 'Pan con relleno'],
  ['pizza', 'Comida italiana redonda'],
  ['hamburguesa', 'Carne entre dos panes'],
  ['taco', 'Comida mexicana enrollada'],
  ['paella', 'Arroz español con azafrán'],
  ['tortilla', 'Huevo batido frito'],
  ['gazpacho', 'Sopa fría de tomate'],
  ['jamón', 'Carne curada española'],
  ['chorizo', 'Embutido rojo picante'],
  ['salchicha', 'Carne en forma de tubo'],
  ['pescado', 'Comida del río o mar'],
  ['atún', 'Pez grande en lata'],
  ['sardina', 'Pez pequeño en lata'],
  ['gamba', 'Marisco rosado pequeño'],
  ['mejillón', 'Marisco de concha negra'],
  ['almeja', 'Marisco de concha'],
  ['ostra', 'Marisco que da perlas'],
  ['langosta', 'Marisco grande con pinzas'],
  ['cangrejo', 'Marisco con caparazón'],
  ['pulpo', 'Ocho brazos en el plato'],
  ['calamar', 'Marisco con tentáculos'],
  ['anchoa', 'Pequeño pez salado'],
  ['bacalao', 'Pescado salado del norte'],
  ['merluza', 'Pescado blanco común'],
  ['lubina', 'Pescado de roca'],
  ['dorada', 'Pescado dorado del mar'],
  ['trucha', 'Pez de río con manchas'],
  ['salmón', 'Pez rosado del norte'],
  ['anguila', 'Pez largo como serpiente'],
  ['tiburón', 'Depredador del océano'],
  ['orca', 'Ballena negra y blanca'],
  ['delfín', 'Mamífero inteligente del mar'],
  ['foca', 'Mamífero marino con bigotes'],
  ['nutria', 'Animal juguetón del río'],
  ['castor', 'Roedor constructor de presas'],
  ['castor', 'Animal de cola plana'],
];

// Trim kid to exactly 200 unique - the list above has duplicates, buildEntries handles that
// Need to ensure we have enough unique words - let me add more if needed
