export default [
  { word: "KATT", clue: "Husdjur som jamar" },
  { word: "HUND", clue: "Husdjur som skäller" },
  { word: "SOL", clue: "Lyser på himlen om dagen" },
  { word: "MANE", clue: "Lyser på himlen om natten" },
  { word: "STJARNA", clue: "Lyser på natthimlen" },
  { word: "TRAD", clue: "Hög växt med löv" },
  { word: "FAGEL", clue: "Djur som flyger" },
  { word: "FISK", clue: "Simmar i vattnet" },
  { word: "BOK", clue: "Du läser sagor i denna" },
  { word: "BOLL", clue: "Rund leksak att kasta" },
  { word: "TARTA", clue: "Sött till födelsedagen" },
  { word: "MJOLK", clue: "Vit dryck från kon" },
  { word: "AGG", clue: "Höns lägger dessa" },
  { word: "ROD", clue: "Färg på ett äpple" },
  { word: "BLA", clue: "Färg på himlen" },
  { word: "HAND", clue: "Du har fem fingrar på varje" },
  { word: "FOT", clue: "Du går med dessa" },
  { word: "NASA", clue: "Du luktar med denna" },
  { word: "OGA", clue: "Du ser med detta" },
  { word: "HATT", clue: "Du bär denna på huvudet" },
  { word: "SANG", clue: "Där du sover" },
  { word: "MUGG", clue: "Du dricker ur denna" },
  { word: "LEKSAK", clue: "Något roligt att leka med" },
  { word: "SPRINGA", clue: "Röra sig snabbt" },
  { word: "HOPPA", clue: "Hoppa upp i luften" },
  { word: "SJUNGA", clue: "Göra musik med rösten" },
  { word: "LEKA", clue: "Ha kul med spel" },
  { word: "REGN", clue: "Vatten som faller från molnen" },
  { word: "SNO", clue: "Vita flingor på vintern" },
  { word: "GRODA", clue: "Grönt djur som hoppar" },
  { word: "BJORN", clue: "Stort lurvigt djur" },
  { word: "ANKA", clue: "Fågel som simmar och kvackar" },
  { word: "BAT", clue: "Fordon som flyter på vattnet" },
  { word: "BIL", clue: "Fordon med hjul" },
  { word: "BUSS", clue: "Stort fordon för många" },
  { word: "PENNA", clue: "Du skriver med denna" },
  { word: "KARTA", clue: "Visar var platser finns" },
  { word: "NYCKEL", clue: "Öppnar ett lås" },
  { word: "LADA", clue: "Behållare med lock" },
  { word: "VASKA", clue: "Du bär saker i denna" },
  { word: "KO", clue: "Gårdsdjur som ger mjölk" },
  { word: "GRIS", clue: "Rosa gårdsdjur" },
  { word: "HONA", clue: "Fågel som lägger ägg" },
  { word: "BI", clue: "Insekt som gör honung" },
  { word: "MYRA", clue: "Litet insekt i kolonier" },
  { word: "UGGLA", clue: "Nattfågel som uvar" },
  { word: "RAV", clue: "Listigt skogsdjur" },
  { word: "LEJON", clue: "Djungelns kung" },
  { word: "ELD", clue: "Het och lysande" },
  { word: "VIND", clue: "Luft i rörelse" },
  { word: "SAND", clue: "Finns på stranden" },
  { word: "STEN", clue: "Hård klippa på marken" },
  { word: "LOV", clue: "Grön del av trädet" },
  { word: "FRO", clue: "Växer till en ny planta" },
  { word: "GARD", clue: "Plats med djur och grödor" },
  { word: "PARK", clue: "Grön plats att leka på" },
  { word: "HEM", clue: "Där du bor" },
  { word: "DORR", clue: "Du öppnar denna för att gå in" },
  { word: "VAGG", clue: "Sida av ett rum" },
  { word: "TAK", clue: "Översta delen av huset" },
  { word: "MAMMA", clue: "Kvinnlig förälder" },
  { word: "PAPPA", clue: "Manlig förälder" },
  { word: "BARN", clue: "Ung människa" },
  { word: "SYSKON", clue: "Bror eller syster" },
  { word: "FARMOR", clue: "Mammas eller pappas mamma" },
  { word: "FARFAR", clue: "Pappas pappa" },
  { word: "MORMOR", clue: "Mammas mamma" },
  { word: "MORFAR", clue: "Mammas pappa" },
  { word: "KUSIN", clue: "Barn till moster eller morbror" },
  { word: "VAN", clue: "Person du tycker om" },
  { word: "LARARE", clue: "Undervisar i skolan" },
  { word: "SKOLA", clue: "Plats för lärande" },
  { word: "BANK", clue: "Du sitter på denna i klassrummet" },
  { word: "BORD", clue: "Möbel att äta vid" },
  { word: "STOL", clue: "Möbel att sitta på" },
  { word: "FONSTER", clue: "Glasöppning i väggen" },
  { word: "GOLV", clue: "Du går på detta inomhus" },
  { word: "KOK", clue: "Rum där mat lagas" },
  { word: "BAD", clue: "Rum med badkar eller dusch" },
  { word: "TRADGARD", clue: "Plats med blommor hemma" },
  { word: "BLOMMA", clue: "Färgglad växt" },
  { word: "GRAS", clue: "Grönt på marken" },
  { word: "BUSKE", clue: "Liten trädliknande växt" },
  { word: "APPLE", clue: "Rött eller grönt frukt" },
  { word: "PARON", clue: "Grön frukt i droppform" },
  { word: "BANAN", clue: "Gul böjd frukt" },
  { word: "JORDGUBBE", clue: "Röd somrig bärfrukt" },
  { word: "DRUVA", clue: "Liten frukt i klasar" },
  { word: "APELSIN", clue: "Rund citrusfrukt" },
  { word: "CITRON", clue: "Sur gul citrusfrukt" },
  { word: "MOROT", clue: "Orange rotfrukt" },
  { word: "POTATIS", clue: "Rund rotfrukt till mat" },
  { word: "BROD", clue: "Bakat av mjöl" },
  { word: "OST", clue: "Gul mat från mjölk" },
  { word: "SMOR", clue: "Gult pålägg på bröd" },
  { word: "SOPPA", clue: "Varm vätska att äta" },
  { word: "RIS", clue: "Små vita korn" },
  { word: "PASTA", clue: "Italiensk mat av mjöl" },
  { word: "KAKA", clue: "Söt bakelse" },
  { word: "GLASS", clue: "Kall söt dessert" },
  { word: "GODIS", clue: "Sött att mumsa på" },
  { word: "VATTEN", clue: "Törstig? Drick detta" },
  { word: "JUICE", clue: "Dryck av frukt" },
  { word: "TE", clue: "Varm dryck i kopp" },
  { word: "HONUNG", clue: "Gul söt sak av bin" },
  { word: "SOCKER", clue: "Gör maten söt" },
  { word: "SALT", clue: "Krydda som smakar salt" },
  { word: "GUL", clue: "Färg på solen" },
  { word: "GRON", clue: "Färg på gräset" },
  { word: "VIT", clue: "Färg på snön" },
  { word: "SVART", clue: "Färg på natten" },
  { word: "ROSA", clue: "Ljus röd färg" },
  { word: "LILA", clue: "Blandning av rött och blått" },
  { word: "ORANGE", clue: "Färg mellan röd och gul" },
  { word: "BRUN", clue: "Färg på jord" },
  { word: "GRA", clue: "Färg på moln" },
  { word: "EN", clue: "Första talet" },
  { word: "TVA", clue: "Ett plus ett" },
  { word: "TRE", clue: "Ett plus två" },
  { word: "FYRA", clue: "Ett plus tre" },
  { word: "FEM", clue: "Antal fingrar på en hand" },
  { word: "SEX", clue: "Efter fem, före sju" },
  { word: "SJU", clue: "Dagar i en vecka" },
  { word: "ATTA", clue: "Efter sju" },
  { word: "NIO", clue: "Före tio" },
  { word: "TIO", clue: "Två gånger fem" },
  { word: "HUVUD", clue: "Där hjärnan sitter" },
  { word: "MUN", clue: "Du äter med denna" },
  { word: "ORA", clue: "Du hör med detta" },
  { word: "TAND", clue: "Vit i munnen" },
  { word: "HAR", clue: "Växer på huvudet" },
  { word: "ARM", clue: "Mellan axel och hand" },
  { word: "BEN", clue: "Du står på dessa" },
  { word: "MAGE", clue: "Mitt på kroppen" },
  { word: "HJARTA", clue: "Slår i bröstet" },
  { word: "KNA", clue: "Böjs när du springer" },
  { word: "TA", clue: "Längst ut på foten" },
  { word: "FINGER", clue: "Fem på varje hand" },
  { word: "TUMME", clue: "Kortaste fingret" },
  { word: "KIND", clue: "Rund del av ansiktet" },
  { word: "HALS", clue: "Kopplar huvud och kropp" },
  { word: "RYGG", clue: "Baksidan av kroppen" },
  { word: "LAR", clue: "Övre delen av benet" },
  { word: "SOVA", clue: "Vila med slutna ögon" },
  { word: "ATA", clue: "Få i sig mat" },
  { word: "DRICKA", clue: "Få i sig vätska" },
  { word: "PRATA", clue: "Säga ord" },
  { word: "LYSSNA", clue: "Använda öronen" },
  { word: "SE", clue: "Använda ögonen" },
  { word: "LUKTA", clue: "Använda näsan" },
  { word: "KANNA", clue: "Ta på med händerna" },
  { word: "GA", clue: "Röra sig till fots" },
  { word: "SIMMA", clue: "Röra sig i vattnet" },
  { word: "FLYGA", clue: "Röra sig genom luften" },
  { word: "CYKLA", clue: "Åka på två hjul" },
  { word: "MALA", clue: "Färglägga med pensel" },
  { word: "RITA", clue: "Göra bilder med penna" },
  { word: "LASA", clue: "Titta på ord i bok" },
  { word: "SKRIVA", clue: "Sätta bokstäver på papper" },
  { word: "RAKNA", clue: "Säga tal i ordning" },
  { word: "BYGGA", clue: "Sätta ihop delar" },
  { word: "KASTA", clue: "Skicka något genom luften" },
  { word: "FANGA", clue: "Ta emot något i luften" },
  { word: "KLAPPA", clue: "Slå ihop händerna" },
  { word: "SKRATTA", clue: "Visa glädje med ljud" },
  { word: "GRATA", clue: "Tårar rinner" },
  { word: "KYSSA", clue: "Visa kärlek med munnen" },
  { word: "KRAM", clue: "Hålla om någon" },
  { word: "LE", clue: "Visa glädje i ansiktet" },
  { word: "SKRIKA", clue: "Ropa högt" },
  { word: "DANSA", clue: "Röra kroppen till musik" },
  { word: "SPELA", clue: "Ha roligt med leksaker" },
  { word: "VINNA", clue: "Komma först i tävling" },
  { word: "FORLORA", clue: "Inte vinna" },
  { word: "DELA", clue: "Ge till andra" },
  { word: "HJALPA", clue: "Göra något för någon" },
  { word: "ALSKA", clue: "Tycka mycket om" },
  { word: "ONSKA", clue: "Hoppas på något" },
  { word: "DROMMA", clue: "Se bilder när du sover" },
  { word: "VAKNA", clue: "Sluta sova" },
  { word: "TVATTA", clue: "Göra sig ren med vatten" },
  { word: "BORSTA", clue: "Rengöra tänder eller hår" },
  { word: "KLA", clue: "Sätta på sig kläder" },
  { word: "OPPNA", clue: "Inte stängd" },
  { word: "STANGA", clue: "Inte öppen" },
  { word: "KOMMA", clue: "Anlända" },
  { word: "STANNA", clue: "Inte röra sig" },
  { word: "VANTA", clue: "Stå kvar en stund" },
  { word: "LETA", clue: "Försöka hitta" },
  { word: "HITTA", clue: "Upptäcka det man sökte" },
  { word: "GE", clue: "Överlämna till någon" },
  { word: "FRAGA", clue: "Vill veta något" },
  { word: "SVARA", clue: "Ge svar" },
  { word: "HEJ", clue: "Ord när man möts" },
  { word: "HEJDA", clue: "Ord när man går" },
  { word: "TACK", clue: "Ord av tacksamhet" },
  { word: "SNALLA", clue: "Artigt ord vid önskemål" },
  { word: "JA", clue: "Bekräftande svar" },
  { word: "NEJ", clue: "Förnekande svar" },
  { word: "NAMN", clue: "Vad du kallas" },
];
